### ISSUE TITLE
High CPU usage in APIM-2.1.0

### ISSUE THREAD

**Issue by Prasadi-R** [wso2/andes#1015]
**Description:**
High CPU usage in APIM-2.1.0 due to the used waiting strategy of Disruptor which is BlockingWaitingStrategy. Need to change it to SleepingBlockingWaitStrategy.

**Affected Product Version:**
APIM-2.1.0 - (andes_3.1.6)

**Related Issues:**
https://github.com/wso2/product-ei/issues/1551

**Comment by a5anka** [comment]
This is fixed in https://github.com/wso2/andes/commit/f98f60c2a4e2a1eac128af53bccb9c494367d347
