### ISSUE TITLE
Dependency on Apache Mina 1.1.7

### ISSUE THREAD

**Issue by mirehasfun** [wso2/andes#778]
Hello

In our application, we need to connect to a WSO2 message broker, so we set our app up to use andes-client.jar, according to the 'samples' documentation from the message broker. This works fine and all, but we also need to connect to a LDAP server using Apaches Directory API (https://directory.apache.org/api/).

The problem now is, that andes-client depends on Mina v.1.1.7 whereas the Directory API depends on Mina v.2.0.x - which of course is not compatible.

Do you see any possibility to make andes depend on Mina v.2?

Thx and Regard

**Comment by hastef88** [comment]
We do not have a strict roadmap/ priority to upgrade the mina version from 1.1.7 -> 2.0x at the moment, given that we are not facing any critical issues with the current version. 

However any contributions on the same would be welcome :)

**Comment by mirehasfun** [comment]
Okay, thanks for the info, I'll discuss the next steps with my team and close this issue for the time :)
